from fuzzywuzzy import fuzz
import pandas as pd

# # word = 'mellanni'
# # check = 'melani bed sheets queen size'

# # print(fuzz.ratio(word, check))

threshold = 70

target = "mellanni bedspread"
# filters = target.split(" ")

# search_terms = ['melani bed sheets queen size',
#     'melani bedding',
#     'melani bedsheets',
#     'melani bedskirt',
#     'melani cal ning sheet',
#     'melani california king fitted sheet deep pocket',
#     'melani chevron sheets',
#     'melani clean sheets',
#     'melani coverlet',
#     'melani dark grey sheets',
#     'melani dherts',
#     'melani divet',
#     'melani duvet',
#     'melani duvet cover',
#     'melani fitted sheet king size',
#     'melani flannel sheets',
#     'melani floral sheets set',
#     'melani full sheet set',
#     'melani full size pillow cases',
#     'melani full size sheets',
#     'melani full/queen sheet set',
#     'melani gray sheet full',
#     'melani hotel sheets',
#     'melani iconic king pillow cases',
#     'melani iconic sheet',
#     'melani king bed',
#     'melani king bedsheets',
#     'melani king bedspread',
#     'melani king duvet',
#     'melani king duvet cover set',
#     'melani king duvet covers',
#     'melani king fitted shedt',
#     'melani king fitted sheet',
#     'melani king fitted sheets',
#     'melani king pillow cases',
#     'melani king pillowcase',
#     'melani king pillowcases white',
#     'melani king pillowcases white stripes',
#     'melani king shams white',
#     'melani king sheet',
#     'melani king sheets',
#     'melani king size bed sheets',
#     'melani king size sheets',
#     'melani king spa blue',
#     'melani king white sheets',
#     'melani linen sheets',
#     'melani micro fiber sheets',
#     'melani pillow c case',
#     'melani pillow case',
#     'melani pillow cases',
#     'melani pillow cases standard size',
#     'melani pillowcase',
#     'melani pillowcase king',
#     'melani pillowcases standard',
#     'melani pollow cases',
#     'melani queen bed sheets',
#     'melani queen bed sheets set',
#     'melani queen bedspreads',
#     'melani queen deep pocket sheet',
#     'melani queen duvet',
#     'melani queen fitted sheet',
#     'melani queen pillow cases',
#     'melani queen pillow dheet',
#     'melani queen pillowcases',
#     'melani queen sheet set',
#     'melani queen sheet set ivory new',
#     'melani queen sheets',
#     'melani queen sheets set-4 pc iconic collection',
#     'melani queen top sheet',
#     'melani queen white',
#     'melani red pillow cases set of 2',
#     'melani rv sheets',
#     'melani rwin xl sheet',
#     'melani sheet',
#     'melani sheet queen',
#     'melani sheet sale',
#     'melani sheet set',
#     'melani sheet sets',
#     'melani sheet twin',
#     'melani sheets',
#     'melani sheets camper queen',
#     'melani sheets double',
#     'melani sheets full',
#     'melani sheets full size',
#     'melani sheets queen',
#     'melani sheets queen size bed set',
#     'melani sheets top shert',
#     'melani sheets twin',
#     'melani sheets with deep pockets',
#     'melani sheets wueen white',
#     'melani sheets, king, purple',
#     'melani sheets￼',
#     'melani sherts',
#     'melani sleep set',
#     'melani sleep sheets',
#     'melani soft full set of sheets',
#     'melani standard pillow',
#     'melani standard pillow case',
#     'melani standard pillowcases',
#     'melani standra pillow',
#     'melani tein sheets',
#     'melani twin',
#     'melani twin bed sheet',
#     'melani twin cl fitted sheet',
#     'melani twin duvet set',
#     'melani twin pillow cases',
#     'melani twin pillows cases set of 2',
#     'melani twin sheet',
#     'melani twin sheets',
#     'melani twin sheets set',
#     'melani twin sheets xl',
#     'melani twin xl sheets',
#     'melani white bedsheets',
#     'melani white king duvet covet',
#     'melani white king sheet',
#     'melani white king sheets',
#     'melani white pillow cases king',
#     'melani white queen beed skirt',
#     'melani white sheet',
#     'melani white sheets',
#     'melani white standard pillow case',
#     'melani whote sheets',
#     'melani xl twin bottom sheet',
#     'melania bed sheets',
#     'melania bed sheets king',
#     'melania bed skirt dark grey',
#     'melania fitted sheet',
#     'melania flat queen sheet',
#     'melania king fitted sheet',
#     'melania sheets',
#     'melania sheets full',
#     'melania sheets king',
#     'melania sheets pillow cases',
#     'melania sheets queen',
#     'melania sheets twin',
#     'melania sheets white',
#     'melania white pillow cases',
#     'melanie bed covers',
#     'melanie bed sheets',
#     'melanie bed sheets king',
#     'melanie bed sheets queen',
#     'melanie bedroom sheets',
#     'melanie bedroom sheets￼',
#     'melanie bedsheets',
#     'melanie bedspread coverlet green',
#     'melanie beige pillow case queen',
#     'melanie brown queen sheets',
#     'melanie brown sheets',
#     'melanie brushed microfiber sheets',
#     'melanie cal king size sheets set',
#     'melanie cotton flannel sheets sage geeen',
#     'melanie duvet',
#     'melanie duvet cover',
#     'melanie extra deep pocket sheets',
#     'melanie extra deep pocket sheets king size grey hotel luxury',
#     'melanie fine linens',
#     'melanie fine linens￼',
#     'melanie fine lonens sheets queen',
#     'melanie fitted queen shit',
#     'melanie fitted sheet',
#     'melanie fitted sheet only',
#     'melanie flat sheets queen',
#     'melanie iconic collection sheet',
#     'melanie iconic pillow cases',
#     'melanie iconic pillow cases spa blue',
#     'melanie iconic striped white pillowcases',
#     'melanie king bed sheets',
#     'melanie king duvet sham fitted',
#     'melanie king pillow case',
#     'melanie king pillow cases',
#     'melanie king pillowcases',
#     'melanie king sheet set',
#     'melanie king sheets',
#     'melanie king sheets sets',
#     'melanie king size pillow cases',
#     'melanie king white fitted sheets',
#     'melanie light grey standard pillow case',
#     'melanie microfiber linen',
#     'melanie microfiber sheets￼',
#     'melanie pillow cases',
#     'melanie pillow cases king',
#     'melanie pillow cases purple',
#     'melanie pillow cases spa blue',
#     'melanie pillowcases',
#     'melanie pink flannel bed sheets',
#     'melanie polyester queen sheets',
#     'melanie queen fitted set',
#     'melanie queen fitted sheet',
#     'melanie queen pillow case',
#     'melanie queen pillow cases',
#     'melanie queen sheet',
#     'melanie queen sheet set',
#     'melanie queen sheets',
#     'melanie queen sheets deep pocket spa blue',
#     'melanie queen sheets set',
#     'melanie queen size bed sheets',
#     'melanie set',
#     'melanie sheet',
#     'melanie sheet set',
#     'melanie sheets',
#     'melanie sheets cal king',
#     'melanie sheets for nectar mattress',
#     'melanie sheets for queen size bed',
#     'melanie sheets for queen￼',
#     'melanie sheets full',
#     'melanie sheets full flat',
#     'melanie sheets king',
#     'melanie sheets king bed',
#     'melanie sheets king deep pockets',
#     'melanie sheets light grey',
#     'melanie sheets microfiber',
#     'melanie sheets queen',
#     'melanie sheets queen deep pockets',
#     'melanie sheets queen delivery today',
#     'melanie sheets, queen',
#     'melanie sheets￼',
#     'melanie shhets',
#     'melanie standard pillow cases',
#     'melanie stire king sheets',
#     'melanie top sheets king',
#     'melanie twin sheets',
#     'melanie twin xl sheets',
#     'melanie white 6 piece queen sheets set',
#     'melanie white pillowcases',
#     'melanie white queen pillowcases￼',
#     'melanie white queen sheets',
#     'melanie yellow king pillow pillow cases',
#     'melanii sheets',
#     'melaniking sheet',
#     'melanin california king sheets',
#     'melanin duvet cover',
#     'melanin fitted sheet',
#     'melanin king duvet cover',
#     'melanin king pillow cases',
#     'melanin king pillow cases ivory',
#     'melanin king sheets',
#     'melanin king size sheets',
#     'melanin pillow cases',
#     'melanin queen sheet set',
#     'melanin queen sheet set fitted',
#     'melanin queen sheets',
#     'melanin queen sheets eat',
#     'melanin queen sheets set',
#     'melanin queen sheets set 4',
#     'melanin sheets',
#     'melanin sheets king',
#     'melanin sheets king paisley',
#     'melanin sheets queen',
#     'melanin soft sheets queen',
#     'melanin twin sheets',
#     'melanini sheets',
#     'melanna queen sheets',
#     'melanni',
#     'melanni aueen pillow case',
#     'melanni bed fitted sheets',
#     'melanni bed sheet twin xl',
#     'melanni bed sheets',
#     'melanni bedding',
#     'melanni beige pillow cases',
#     'melanni body pillow case',
#     'melanni brown flat sheet king',
#     'melanni duvet',
#     'melanni duvet cover',
#     'melanni duvet cover white',
#     'melanni extra deep king sheets',
#     'melanni extra deep pocket',
#     'melanni extra deep pocket queen sheet',
#     'melanni extra deep quenn sheets',
#     'melanni extra ling tein',
#     'melanni fine linens',
#     'melanni fitted queen white bed sheet',
#     'melanni fitted sheet',
#     'melanni fitted sheet and pillow',
#     'melanni fitted sheet queen',
#     'melanni full fitted sheet and pillow case',
#     'melanni full sheet sets',
#     'melanni full sized',
#     'melanni full top sheet',
#     'melanni hotel luxury pillowases',
#     'melanni iconic collection sheet set',
#     'melanni king',
#     'melanni king bedspread coverlet set',
#     'melanni king deep pocket fitted sheet',
#     'melanni king duvet whote',
#     'melanni king fitted sheet',
#     'melanni king pillow',
#     'melanni king pillow cases',
#     'melanni king pillow cases 2 pack',
#     'melanni king pillow shams',
#     'melanni king sheet',
#     'melanni king sheets',
#     'melanni king sheets white',
#     'melanni king size pillow cases in coral',
#     'melanni king size sheets set',
#     'melanni king size shieets set',
#     'melanni king top sheet',
#     'melanni light gray duvet',
#     'melanni linens',
#     'melanni pillow case',
#     'melanni pillow case king size',
#     'melanni pillow cases',
#     'melanni pillow cases sage',
#     'melanni pillow cases stamdard size',
#     'melanni pillowcase',
#     'melanni pillowcases',
#     'melanni pillowcase￼',
#     'melanni pilow cases',
#     'melanni queen',
#     'melanni queen bed sheets',
#     'melanni queen duvet',
#     'melanni queen flat sheet',
#     'melanni queen oillow cases',
#     'melanni queen pillow cases',
#     'melanni queen pilowcases',
#     'melanni queen she',
#     'melanni queen sheet set',
#     'melanni queen sheet set hotel',
#     'melanni queen sheet sets',
#     'melanni queen sheets',
#     'melanni queen size extra deep fitted sheet',
#     'melanni quilts for queen beds',
#     'melanni ruffles bedspread',
#     'melanni sheet',
#     'melanni sheet cali king',
#     'melanni sheet cotton',
#     'melanni sheet set',
#     'melanni sheeta',
#     'melanni sheets',
#     'melanni sheets queen',
#     'melanni sheets twin',
#     'melanni sherrs',
#     'melanni shhets',
#     'melanni standard pillow cases',
#     'melanni tein duvet set',
#     'melanni twin bed sheet',
#     'melanni twin pillow case',
#     'melanni twin sheet',
#     'melanni twin sheets',
#     'melanni twin xl deep pocket',
#     'melanni twin xl sheet sets',
#     'melanni twin xl sheets',
#     'melanni white pillow cases',
#     'melanni white pillow cases set of 2',
#     'melanni white queen pillow case',
#     'melanni white queen pillowcase',
#     'melanni white twin fitted sheet',
#     'melanni white twin xl fitted sheet',
#     'melanni white xl twin sheets',
#     'melanni wueen fotted dheet',
#     'melannia fitted sheet',
#     'melannia sheets',
#     'melannie king sheet',
#     'melannie king top sheet',
#     'melannio sheets',
#     'melannni king pillow cases iconic',
#     'melany bed sheets',
#     'melany pillows cases standard size set of 4',
#     'melany queen sheet set',
#     'melany sheets',
#     'melatti sheets',
#     'melellalani sheets',
#     'melellani queen set',
#     'meleni sheets',
#     'meliana sheets',
#     'meliani king sheets',
#     'meliani sheets',
#     'meliani sleep sheets',
#     'meliani twin sheet set',
#     'melianni bedspread',
#     'melianni king pillowcases',
#     'melianni queen sheets',
#     'melianni sheets',
#     'melianni standard size pillow cases',
#     'melianni toddler 3 piece set',
#     'melilinni sheet set with extra pillowcases',
#     'melini pillowcases',
#     'melini sheets',
#     'melini sheets kings size',
#     'melini twin xl sheets set',
#     'melinni queen white sheets',
#     'melinni white sheets queen set',
#     'melioni sheets',
#     'melissani pillowcase',
#     'melkami sheets wueen',
#     'melkani befsherts',
#     'melkani extra derp twin xl',
#     'melkani king shhets',
#     'melkani pillow case',
#     'melkanni wueen sheets',
#     'melkanu top king sheet',
#     'mell sheets',
#     'mella i sheet set',
#     'mella i wueen oullow case',
#     'mellaanno fitted sheet',
#     'mellabi hotel sheets',
#     'mellabi pillow cases light grey',
#     'mellain sheets',
#     'mellaine king sheets',
#     'mellaini',
#     'mellaini microfiber sheets queen size',
#     'mellaini sheets',
#     'mellainni sonic bedspread cal king',
#     'mellalani elastic fitted sheet',
#     'mellalani sheets',
#     'mellalini standard size pillow cases',
#     'mellami duvet cover queen size',
#     'mellami king deep pocket fitted sheet',
#     'mellami king sheets',
#     'mellami pillow',
#     'mellami pillow cases',
#     'mellami pillowcase',
#     'mellami pillowcases',
#     'mellami queen',
#     'mellami queen sheets',
#     'mellami sheets',
#     'mellami sheets queen',
#     'mellami sheets sets queen',
#     'mellami shieets',
#     'mellami teal pillow cases',
#     'mellami twin fitted sheet',
#     'mellami twin xl duvet cover',
#     'mellami white pillow cases',
#     'mellamia duvet cover',
#     'mellamni king shams',
#     'mellan i light grey bed skirt',
#     'mellan i white microfiber pillow',
#     'mellan pillow cases whte standard',
#     'mellan standard pillow cases in blue hydrangea',
#     'mellana sheets',
#     'mellanbi bed skirt',
#     'mellani',
#     'mellani 1 set of king sheets',
#     'mellani 10 piece',
#     'mellani 1102 pillowcases',
#     'mellani 14" depth king sheets',
#     'mellani 15 in bed skirt',
#     'mellani 2 king pillow',
#     'mellani 3 piece iconic collection',
#     'mellani 368',
#     'mellani 4 piece king pillow case',
#     'mellani 4 pillowcase',
#     'mellani 4 sheets set twin xl',
#     'mellani 6 piece wueen set sheets',
#     'mellani agua standard pillowcase',
#     'mellani aheets',
#     'mellani bamboo sheet set full white',
#     'mellani bamboo sheets',
#     'mellani bed',
#     'mellani bed aheeta',
#     'mellani bed aheets',
#     'mellani bed cover',
#     'mellani bed covers',
#     'mellani bed sheet',
#     'mellani bed sheet (queen)',
#     'mellani bed sheet full',
#     'mellani bed sheet pillows',
#     'mellani bed sheet set',
#     'mellani bed sheet set + silk pillowcase bundle',
#     'mellani bed sheet set queen',
#     'mellani bed sheet taupe king fitted sheet',
#     'mellani bed sheets',
#     'mellani bed sheets cal king',
#     'mellani bed sheets king',
#     'mellani bed sheets king size',
#     'mellani bed sheets queen',
#     'mellani bed sheeys',
#     'mellani bed shhets full',
#     'mellani bed skirt',
#     'mellani bed skirt cal king',
#     'mellani bed skirt fll size tailored drop skirt',
#     'mellani bed skirt king',
#     'mellani bed skirt twin xl blue hydrangea',
#     'mellani bed skirts',
#     'mellani bedding',
#     'mellani bedding full size',
#     'mellani bedding set',
#     'mellani bedroom sheets',
#     'mellani bedsheet',
#     'mellani bedsheets',
#     'mellani bedspread',
#     'mellani bedspread coverlet set twin',
#     'mellani beige pillow case',
#     'mellani beige sheets',
#     'mellani bes sheets',
#     'mellani best sheets',
#     'mellani black pillow cases',
#     'mellani black queen size bed skirt',
#     'mellani black twin sheets',
#     'mellani blue hydrangea pillow cases',
#     'mellani blue hydrangea queen',
#     'mellani blue hydregia king pillowcases',
#     'mellani blue king pillowcases',
#     'mellani blue nova pillow cases',
#     'mellani blush pillowcase',
#     'mellani body pillow',
#     'mellani body pillow case',
#     'mellani brand standard/quefn pillow cases',
# ]


# conditions = [all([any([[fuzz.ratio(filter, word.lower())>threshold for filter in filters] for word in search_term.split(" ")])]) for search_term in search_terms]

# top_list = []
# for search_term in search_terms:
#     words = search_term.split(" ")
#     inner_list = []
#     for filter in filters:
#         temp = []
#         if any([fuzz.ratio(filter, word.lower())>threshold for word in words]):
#             temp.append(True)
#         else:
#             temp.append(False)
#         inner_list.append(any(temp))
#     top_list.append(all(inner_list))
 
# # print("Top List: ", top_list)
# for i, condition in enumerate(top_list):
#     if condition:
#         print(search_terms[i])


def is_similar(search_term, target, threshold=75):
    """
    Check if the search term is similar to the target based on a given threshold.
    """
    words = search_term.lower().split()
    targets = target.lower().split()
    return all([any([fuzz.ratio(search_term, word)>=threshold for word in words]) for search_term in targets])


df = pd.read_excel('/home/misunderstood/Downloads/SQP_data (2).xlsx', sheet_name="Search Query") #change path to your SQP file

bool_mask = df['Search Query'].apply(lambda x: is_similar(x, target, threshold=threshold))

print(df[bool_mask])