sales_columns = ['(parent)_asin', '(child)_asin', 'title', 'sku',
       'sessions_-_mobile_app', 'sessions_-_mobile_app_-_b2b',
       'sessions_-_browser', 'sessions_-_browser_-_b2b', 'sessions_-_total',
       'sessions_-_total_-_b2b', 'session_percentage_-_mobile_app',
       'session_percentage_-_mobile_app_-_b2b', 'session_percentage_-_browser',
       'session_percentage_-_browser_-_b2b', 'session_percentage_-_total',
       'session_percentage_-_total_-_b2b', 'page_views_-_mobile_app',
       'page_views_-_mobile_app_-_b2b', 'page_views_-_browser',
       'page_views_-_browser_-_b2b', 'page_views_-_total',
       'page_views_-_total_-_b2b', 'page_views_percentage_-_mobile_app',
       'page_views_percentage_-_mobile_app_-_b2b',
       'page_views_percentage_-_browser',
       'page_views_percentage_-_browser_-_b2b',
       'page_views_percentage_-_total', 'page_views_percentage_-_total_-_b2b',
       'featured_offer_(buy_box)_percentage',
       'featured_offer_(buy_box)_percentage_-_b2b', 'units_ordered',
       'units_ordered_-_b2b', 'units_session_percentage',
       'ordered_product_sales',
       'ordered_product_sales_-_b2b', 'total_order_items',
       'total_order_items_-_b2b', 'date', 'units_session_percentage_-_b2b']


fba_inventory_columns = ['snapshot-date', 'sku', 'fnsku', 'asin', 'product-name', 'condition',
       'available', 'pending-removal-quantity', 'inv-age-0-to-90-days',
       'inv-age-91-to-180-days', 'inv-age-181-to-270-days',
       'inv-age-271-to-365-days', 'inv-age-365-plus-days', 'currency',
       'units-shipped-t7', 'units-shipped-t30', 'units-shipped-t60',
       'units-shipped-t90', 'alert', 'your-price', 'sales-price',
       'lowest-price-new-plus-shipping', 'lowest-price-used',
       'recommended-action', 'healthy-inventory-level',
       'recommended-sales-price', 'recommended-sale-duration-days',
       'recommended-removal-quantity',
       'estimated-cost-savings-of-recommended-actions', 'sell-through',
       'item-volume', 'volume-unit-measurement', 'storage-type',
       'storage-volume', 'marketplace', 'product-group', 'sales-rank',
       'days-of-supply', 'estimated-excess-quantity', 'weeks-of-cover-t30',
       'weeks-of-cover-t90', 'featuredoffer-price',
       'sales-shipped-last-7-days', 'sales-shipped-last-30-days',
       'sales-shipped-last-60-days', 'sales-shipped-last-90-days',
       'inv-age-0-to-30-days', 'inv-age-31-to-60-days',
       'inv-age-61-to-90-days', 'inv-age-181-to-330-days',
       'inv-age-331-to-365-days', 'estimated-storage-cost-next-month',
       'inbound-quantity', 'inbound-working', 'inbound-shipped',
       'inbound-received', 'total_reserved_quantity', 'unfulfillable-quantity',
       'quantity-to-be-charged-ais-181-210-days', 'estimated-ais-181-210-days',
       'quantity-to-be-charged-ais-211-240-days', 'estimated-ais-211-240-days',
       'quantity-to-be-charged-ais-241-270-days', 'estimated-ais-241-270-days',
       'quantity-to-be-charged-ais-271-300-days', 'estimated-ais-271-300-days',
       'quantity-to-be-charged-ais-301-330-days', 'estimated-ais-301-330-days',
       'quantity-to-be-charged-ais-331-365-days', 'estimated-ais-331-365-days',
       'quantity-to-be-charged-ais-365-plus-days',
       'estimated-ais-365-plus-days', 'historical-days-of-supply',
       'recommended_ship-in_quantity', 'recommended_ship-in_date',
       'last_updated_date_for_historical_days_of_supply',
       'exempted_from_low-inventory-level_fee?',
       'low-inventory-level_fee_applied_in_current_week?',
       'short_term_historical_days_of_supply',
       'long_term_historical_days_of_supply', 'inventory_age_snapshot_date',
       'inventory_supply_at_fba', 'reserved_fc_transfer',
       'reserved_fc_processing', 'reserved_customer_order',
       'total_days_of_supply_(including_units_from_open_shipments)']